import { League_Spartan, Jost } from "next/font/google";
import "./globals.css";

const myFont = League_Spartan({
  subsets: ["latin"],
  variable: "--font-spartan",
});

const myFont2 = Jost({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-jost",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${myFont.variable} ${myFont2.variable}`}>
      <head>
        <link
          href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
          rel="stylesheet"
        />
      </head>

      <body>{children}</body>
    </html>
  );
}
